### ISSUE TITLE
Can't open the preferences menu

### ISSUE THREAD

**Issue by brainwo** [phuang/ibus-pinyin#27]
When I click on "Preferences" button in Input Method section in IBus Preferences, nothing happened.
Further investigation got me this log running IBus Preferences from the terminal:
```
/usr/share/ibus-pinyin/setup/main.py:
29: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/share/ibus-pinyin/setup/main.py:30: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import IBus
Traceback (most recent call last):
  File "/usr/share/ibus-pinyin/setup/main.py", line 426, in <module>
    main()
  File "/usr/share/ibus-pinyin/setup/main.py", line 422, in main
    PreferencesDialog(name).run()
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/ibus-pinyin/setup/main.py", line 42, in __init__
    gettext.bind_textdomain_codeset("ibus-pinyin", "UTF-8")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'
```
System information:
```
Arch Linux 6.4.10
ibus 1.5.28-4
ibus-pinyin 1.5.0-8
```
Another input method Anthy can open the preferences menu just fine.

**Comment by hosiet** [comment]
https://github.com/ibus/ibus-pinyin/commit/e2e10c40

Please ask your Arch Linux package maintainer to include the patch.
